source 'https://rubygems.org'

gem 'activerecord'
gem 'pg'
gem 'rake'
gem 'active_record_migrations'
gem 'pry'
gem 'tweetstream'
gem 'twitter'
gem 'dotenv'
gem 'civic_aide'
gem 'opensecrets'
gem 'rest_client'
gem 'nokogiri'
gem "foreman"
gem 'people'
