development:
  adapter: postgresql
  database: whosmyrep_console_development

test:
  adapter: postgresql
  database: whosmyrep_console_test

production:
  adapter: postgresql
  database: whosmyrep_console_production

